In [22]:
import pandas as pd
import json
import requests

url ='https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population'
def get_url(url):
    df = pd.read_html(url)
    df1 = df[0].iloc[0:,1:3]  # to take out the columns not needed
    df2 = pd.DataFrame(df1)
    df2.to_csv('countries.csv', index=False ,header=False)
    return df2
get_url(url)

                    Country / Dependency    Region
0                                  World       NaN
1                                  China      Asia
2                                  India      Asia
3                          United States  Americas
4                           Indonesia[b]      Asia
..                                   ...       ...
237                   Niue (New Zealand)   Oceania
238                Tokelau (New Zealand)   Oceania
239                         Vatican City    Europe
240  Cocos (Keeling) Islands (Australia)   Oceania
241    Pitcairn Islands (United Kingdom)   Oceania

[242 rows x 2 columns]